### ISSUE TITLE
Exception not handled

### ISSUE THREAD

**Issue by hakavlad** [tobixen/thrash-protect#23]
```
ERROR:root:red alert!  unacceptable time delta observed! interval: 0.5 cooldown_counter: 1 expected delay: 0 delta: 0.0539078712463 time: 1552620438.78 frozen pids: [(27290, 27295), (27290, 27765), (1042,), (1747,), (27240,)]
ERROR:root:Could not fetch process user information
Traceback (most recent call last):
  File "./thrash-protect.py", line 409, in get_process_info
    info = check_output("ps -p %d uf" % pid, shell = True).decode('utf-8')
  File "/usr/lib/python2.7/subprocess.py", line 219, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
CalledProcessError: Command 'ps -p 27295 uf' returned non-zero exit status 1
ERROR:root:red alert!  unacceptable time delta observed! interval: 0.5 cooldown_counter: 0 expected delay: 0 delta: 0.149600982666 time: 1552620439.35 frozen pids: [(27290, 27765), (1042,), (1747,), (27240,)]
ERROR:root:red alert!  unacceptable time delta observed! interval: 0.5 cooldown_counter: 1 expected delay: 0 delta: 0.0599908828735 time: 1552620440.44 frozen pids: [(27290, 27765), (1042,), (1747,), (27240,)]
```

**Comment by tobixen** [comment]
The exception is indeed handled, the traceback is printed because the parameter exc_info=True is passed to the logger.

One possible reason why the ps command would fail is that the process has already exited when we get to this point.

I'll edit the error message and skip logging the traceback.
